apiVersion: apps/v1
kind: Deployment
metadata:
  name: medecin-consultation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medecin-consultation-service
  template:
    metadata:
      labels:
        app: medecin-consultation-service
    spec:
      containers:
        - name: medecin-consultation-service
          image: najlaebk1/consultation_images
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8762/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service.default.svc.cluster.local:9999
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
---
apiVersion: v1
kind: Service
metadata:
  name: medecin-consultation-service
spec:
  selector:
    app: medecin-consultation-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer